
title: Conghui He
url: 'http://conghui.github.com'
# baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
# style: styles-4
# style: styles-5
# style: styles-6


#Profile information
name: Conghui He
tagline: PhD Candidate
pic: 01_CH_320x320.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: heconghui@gmail.com
phone: '(+86) 15311775057'
website: conghui.github.com #do not add http://
linkedin: heconghui
github: conghui
twitter: '@_conghui'


# Tracker
#analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
